import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import Sidebar from "./components/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "NodejsWiki",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="grid__container overflow-y-scroll">
          <Header />
          <Sidebar />
          <main className="main bg-[rgba(13,18,28,1)] -z-10">
            <div className="absolute inset-0 -z-10 h-full w-full bg-[rgba(13,18,28,1)] bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]"></div>
            <div className="absolute bottom-[90px] right-[100px] h-[200px] w-[300px] rounded-full blur-[290px] bg-[#EE5389] -z-10"></div>
            {children}
            <div className="absolute top-[90px] -left-[20px] h-[200px] w-[300px] rounded-full blur-[290px] bg-[purple] -z-10"></div>
          </main>
          <div className="h-screen"></div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
